/*
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OrderPaymentAmount;
import org.openapitools.client.model.PaymentCcInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ImportOrderRequestImportedPayment
 */
public class ImportOrderRequestImportedPaymentTest {
    private final ImportOrderRequestImportedPayment model = new ImportOrderRequestImportedPayment();

    /**
     * Model tests for ImportOrderRequestImportedPayment
     */
    @Test
    public void testImportOrderRequestImportedPayment() {
        // TODO: test ImportOrderRequestImportedPayment
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'additionalInfo'
     */
    @Test
    public void additionalInfoTest() {
        // TODO: test additionalInfo
    }

    /**
     * Test the property 'amounts'
     */
    @Test
    public void amountsTest() {
        // TODO: test amounts
    }

    /**
     * Test the property 'ccInfo'
     */
    @Test
    public void ccInfoTest() {
        // TODO: test ccInfo
    }

}
