/*
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OrderPostalAddress;
import org.openapitools.client.model.OrderShipmentItem;
import org.openapitools.client.model.ShipmentTracking;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderShipment
 */
public class OrderShipmentTest {
    private final OrderShipment model = new OrderShipment();

    /**
     * Model tests for OrderShipment
     */
    @Test
    public void testOrderShipment() {
        // TODO: test OrderShipment
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'fromAddress'
     */
    @Test
    public void fromAddressTest() {
        // TODO: test fromAddress
    }

    /**
     * Test the property 'returnAddress'
     */
    @Test
    public void returnAddressTest() {
        // TODO: test returnAddress
    }

    /**
     * Test the property 'tracking'
     */
    @Test
    public void trackingTest() {
        // TODO: test tracking
    }

    /**
     * Test the property 'returnTracking'
     */
    @Test
    public void returnTrackingTest() {
        // TODO: test returnTracking
    }

}
