/*
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OrderOrderBy;
import org.openapitools.client.model.OrderPaymentFilter;
import org.openapitools.client.model.OrderStatusFilter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderSearchOrdersRequest
 */
public class OrderSearchOrdersRequestTest {
    private final OrderSearchOrdersRequest model = new OrderSearchOrdersRequest();

    /**
     * Model tests for OrderSearchOrdersRequest
     */
    @Test
    public void testOrderSearchOrdersRequest() {
        // TODO: test OrderSearchOrdersRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'searchQuery'
     */
    @Test
    public void searchQueryTest() {
        // TODO: test searchQuery
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'pageToken'
     */
    @Test
    public void pageTokenTest() {
        // TODO: test pageToken
    }

    /**
     * Test the property 'orderBy'
     */
    @Test
    public void orderByTest() {
        // TODO: test orderBy
    }

    /**
     * Test the property 'statusFilter'
     */
    @Test
    public void statusFilterTest() {
        // TODO: test statusFilter
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    public void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    public void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'paymentFilter'
     */
    @Test
    public void paymentFilterTest() {
        // TODO: test paymentFilter
    }

    /**
     * Test the property 'agentGrn'
     */
    @Test
    public void agentGrnTest() {
        // TODO: test agentGrn
    }

}
