/*
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.OrderCreateRefundRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OrderCalculateRefundResponse
 */
public class OrderCalculateRefundResponseTest {
    private final OrderCalculateRefundResponse model = new OrderCalculateRefundResponse();

    /**
     * Model tests for OrderCalculateRefundResponse
     */
    @Test
    public void testOrderCalculateRefundResponse() {
        // TODO: test OrderCalculateRefundResponse
    }

    /**
     * Test the property 'createRefundRequest'
     */
    @Test
    public void createRefundRequestTest() {
        // TODO: test createRefundRequest
    }

}
