/*
 * order Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.OptionImage;
import org.openapitools.client.model.OrderMoney;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductConfigurationStepOption
 */
public class ProductConfigurationStepOptionTest {
    private final ProductConfigurationStepOption model = new ProductConfigurationStepOption();

    /**
     * Model tests for ProductConfigurationStepOption
     */
    @Test
    public void testProductConfigurationStepOption() {
        // TODO: test ProductConfigurationStepOption
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'grn'
     */
    @Test
    public void grnTest() {
        // TODO: test grn
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'priceVariation'
     */
    @Test
    public void priceVariationTest() {
        // TODO: test priceVariation
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'hasQuantity'
     */
    @Test
    public void hasQuantityTest() {
        // TODO: test hasQuantity
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

}
